import {choc, replace_content, lindt, DOM, on, apply_fixes} from "https://rosuav.github.io/choc/factory.js";
const {BUTTON, DIV} = lindt; //autoimport

apply_fixes({close_selector: ".dialog_cancel,.dialog_close", click_outside: "formless", methods: 1});

//The content generated by Markdown is hidden in CSS, and we will generate our own main element to put our content into.
const main = document.body.appendChild(choc.MAIN({class: "main-content"}));
//Grab everything out of the Markdown main, and key it by the ID of the most recent heading.
//NOTE: If/when these get used in a replace_content call, they will be removed from their original
//place in the DOM. Don't do that with any structural elements (which should all land in markdown[""]).
const markdown = (() => {
	const markdown = { };
	let cur = markdown[""] = [];
	for (let el = DOM("#content").firstElementChild; el; el = el.nextElementSibling) {
		if (el.tagName[0] === "H" && +el.tagName.slice(1) >= 2) //Headings at level 2 or above become new blocks
			cur = markdown[el.id] = [];
		cur.push(el);
	}
	return markdown;
})();

const state = {scene: "intro"};

const destlabels = {
	crimescene: "The Crime Scene",
	shop: "Local shop",
	fission: "Fish-and-chippery",
};
const defaultdest = Object.keys(destlabels);
function TRAVELBUTTONS(dest) {
	let have_dest = false;
	(dest||defaultdest).forEach(d => !state[d] && (have_dest = true));
	return DIV({class: "travelbuttons"}, [
		"Travel to: ",
		(dest||defaultdest).map(d => BUTTON({type: "button", "data-dest": d, disabled: !!state[d]}, destlabels[d])),
		!have_dest && BUTTON({type: "button", "data-dest": "denoument"}, "Announce your results"),
	]);
}

const scenes = {
	intro() {return [
		markdown["part-one-the-shocking-discovery"],
		TRAVELBUTTONS(["crimescene"]),
	]},
	crimescene() {return [
		markdown["part-two-the-crime-scene"],
		TRAVELBUTTONS(),
	]},
	shop() {return [
		markdown["shop"],
		TRAVELBUTTONS(),
	]},
	fission() {return [
		markdown["fish-and-chippery"],
		TRAVELBUTTONS(),
	]},
	denoument() {return [
		markdown["submit-your-findings"],
		//TODO: This is where you select a person to accuse (or "no crime happened" but maybe disable that
		//because the cat will always see that it's a crime to have no tuna), list the supporting evidence,
		//and submit the case to the human.
	]},
}

function repaint() {
	replace_content(main, scenes[state.scene]());
}
repaint();

on("click", "[data-dest]", e => {
	//Travel to a new location
	state.scene = e.match.dataset.dest;
	state[state.scene] = { };
	repaint();
});
