import {choc, replace_content, lindt, DOM, on, apply_fixes} from "https://rosuav.github.io/choc/factory.js";
const {BUTTON, DIALOG, DIV, H3, HEADER, IMG, P, SECTION, SPAN} = lindt; //autoimport

document.body.appendChild(replace_content(null, DIALOG({id: "inspectdlg"}, SECTION([
	HEADER([H3("Inspect"), DIV([BUTTON({type: "button", class: "dialog_cancel"}, "x")])]),
	DIV({id: "inspectinfo"}, "loading..."),
	P({class: "dlgbuttonbox"}, [BUTTON({class: "dialog_close"}, "Close"), BUTTON({id: "inspect-full"}, "Inspect fully")]),
]))));
document.body.appendChild(replace_content(null, DIALOG({id: "notesdlg"}, SECTION([
	HEADER([H3("My excellent notes"), DIV([BUTTON({type: "button", class: "dialog_cancel"}, "x")])]),
	DIV({id: "notesinfo"}),
	P({class: "dlgbuttonbox"}, [BUTTON({class: "dialog_close"}, "Okay, we're good.")]),
]))));
apply_fixes({close_selector: ".dialog_cancel,.dialog_close", click_outside: "formless", methods: 1});

//The content generated by Markdown is hidden in CSS, and we will generate our own main element to put our content into.
const main = document.body.appendChild(choc.MAIN({class: "main-content"}));
//Grab everything out of the Markdown main, and key it by the ID of the most recent heading.
//NOTE: If/when these get used in a replace_content call, they will be removed from their original
//place in the DOM. Don't do that with any structural elements (which should all land in markdown[""]).

function transform_links(el) {
	if (el.tagName === "A") return el.replaceWith(choc.BUTTON( //TODO: Don't do this if it's actually an external link
		{"data-investigate": el.getAttribute("href")},
		[...el.childNodes],
	));
	[...el.children].forEach(transform_links);
}

const markdown = (() => {
	const markdown = { };
	let cur = markdown[""] = [];
	for (let el = DOM("#content").firstElementChild; el; el = el.nextElementSibling) {
		if (el.tagName[0] === "H" && +el.tagName.slice(1) >= 2) //Headings at level 2 or above become new blocks
			cur = markdown[el.id] = [];
		cur.push(el);
		transform_links(el);
	}
	return markdown;
})();

const state = {scene: "intro"};
let here = { }; //Same as state[state.scene] once we're in a location.

const locations = {
	crimescene: {
		dest: "The Crime Scene", //Label for the button that you click to get here
		time_limit: "Amount of investigation time available in this location",
		time_min: "Minimum investigation before the travel buttons unlock",
		//(For the tutorial, both of them are forced to be equal to the number of investigatables.)
	},
	shop: {
		dest: "Local shop",
		time_limit: 3,
		time_min: 2,
	},
	fission: {
		dest: "Fish-and-chippery",
		time_limit: 3,
		time_min: 1,
	},
};
const all_locations = Object.keys(locations); //We'll use this in a few places; easier to lock it in once.
let loc; //Same as locations[state.scene]

//Basic investigation info is what you can see from a cursory glance. It is unaffected by any
//form of randomization - it will be the same text every time you play the game. Further details
//can be learned by spending time.
const investigate_basic = {
	crimescene: {
		foodbowl: P("An empty food bowl. I don't know how the humans expect a cat to survive without tuna."),
		cupboard: P("A kitchen cupboard at floor level. It's ajar; you could nudge it open with your nose if you want."),
		adult: P("A full size human that regularly enters and leaves this house as if it owns the place."),
		child: P("A reduced-size human that stays here. Talks to us with a high pitched voice."),
		vase: P("On the mantlepiece, there's a vase. It would make a delicious sound if it hit the ground."),
		fridge: P("The fridge, a place where the humans keep food. It is closed."),
	},
	shop: {
		shopkeeper: P("Looks like a person. Hides behind some clanking mechanical stuff. Our humans go here before leaving the shop."),
		yuck_vegetable: P("Don't know what this vegetable is but it smells bad, tastes worse, and isn't even good for expelling hairballs."),
		crisp_vegetable: P("I'd love to stop and chew on this for a bit, but we have to find the tuna."),
		pungent_boxes: P("I think these boxes contain food. Smells ... interesting."),
		tuna: P("This is where the tuna should be. It's up at human height for some reason."),
		customers: P("Several people here, probably trying to buy tuna for their own cats."),
	},
	fission: {
		counter: P("Too high to see over, but you could jump up onto it and have a look."),
		customers: P("They're talking, probably figuring out the best type of fish to eat."),
		staff: P("They dunk the fish in oil. I think they do other things too but mostly fish."),
		diners: P("One of the people looks familiar. Might be worth talking to her."),
		footprints: P("There are footprints on the floor! Not yours! They may be human!"),
	},
};
//For the tutorial, you are always both allowed and required to investigate everything.
locations.crimescene.time_limit = locations.crimescene.time_min = Object.keys(investigate_basic.crimescene).length;

//Unlike basic investigation, these are functions, and may manipulate state.
//(Decrementing time is done automatically.)
const investigate_full = {
	crimescene: {
		foodbowl: () => [
			P([
				"On closer inspection, you see dry cat food, but you can also see the bottom of the ",
				"bowl, so that means it's practically empty. The cat is literally starving, I tell you.",
			]),
		],
		cupboard: () => [
			P([
				"Inside the cupboard are various unpleasant-smelling boxes, a few old sponges that you ",
				"could tear to pieces if you wanted to make a mess, and no cans of tuna. Disappointing.",
			]),
		],
		adult: () => [
			P([
				//Suspect: The adult failed to provide food for no reason.
				"Humans normally are expected to refill food bowls. It's their most important task, and ",
				"this one is not doing it. There must be a reason. Might be that the human's broken.",
			]),
		],
		child: () => [
			P([
				//Increased time cost?
				"As you approach the small human, it reaches down to pick you up. You speak loudly, ",
				"insisting that you do not want uppies right now, but it tries to pick you up anyway. ",
				"There's a short chase around the house before the human gives up. What a waste of time.",
			]),
		],
		vase: () => [
			P("Let's make sure that gravity is working properly today."),
			P({style: "font-style: italic; font-size: 24pt; color: #bb0"}, "<< CRASH >>"),
			P("Yep. Ahh, that was satisfying."),
		],
		fridge: () => [
			P([
				//Increased time cost?
				"Unfortunately for you, the fridge is very difficult to open. You wait around near it ",
				"until one of the humans comes by, then politely request that it be opened so you can ",
				"investigate. The small human says 'No', a word of unclear meaning, and then opens the ",
				"door. Finally. You sniff around, but there's no tuna anywhere. Not really a surprise; ",
				"it usually comes from cans.",
			]),
		],
	},
	shop: {
		shopkeeper: () => [
			P([
				//Suspect: The shopkeeper refused sale.
				//Possible evidence: Empty shelves, no tuna in stock
				"It's possible that this person refused to provide tuna.",
			]),
		],
		yuck_vegetable: () => P([
			"You perform your vital duties of verifying that gravity is still in effect by knocking a ",
			"bit of it onto the floor, only to receive an unpleasant look and a heavy sigh from a nearby human. ",
			"They're ungrateful, and all you got for your trouble was a bitter taste.",
		]),
		crisp_vegetable: () => P([
			"You nudge one of these lovely things onto the floor. One of the nearby humans sighs loudly, ",
			"but doesn't stop you. You enjoy making some marks in it.",
		]),
		pungent_boxes: () => P([
			"I think they smell like soap. What does soap smell like, again?",
		]),
		tuna: () => [
			//Potential evidence. For now assuming that it isn't the cause.
			P([
				"Jumping up onto a shelf, you nudge your nose against the row of cans, counting them. ",
				"The massive clatter on the floor sounded like about twenty, so there's clearly no lack ",
				"of tuna at the shop.",
			]),
		],
		customers: () => P([
			//For now just a red herring but this might give you some other suspects to investigate.
			//"It's just a human. Probably useless.", //use this somewhere
			"There are a few humans around. Interviewing them has resulted in zero responses, but two people ",
			"rubbed by head, so that was something.",
		]),
	},
	fission: {
		counter: () => P([
			"You jump up onto the counter, only to get shooed away. Not with a literal shoe, fortunately - not this time.",
		]),
		customers: () => P([
			//Possible suspect: A customer seen here who eats far too much tuna and stole all the cans.
			"You walk up to each of the humans, rub yourself against their legs, and determine that they're all innocent.",
		]),
		staff: () => P([
			//Possible suspect: A staff member ran out of fish, bought more, and got misdelivery of the cans.
			"They're very busy, and you're a little apprehensive about the kind of unfriendly welcome you might get.",
		]),
		diners: () => [
			//Never a suspect. This is JUST a red herring.
			P("You recognize her. She's a doctor named Lyn, and she likes cats."),
			P([
				"In fact, you've seen her at the Institute, where she and a very long cat (and a rice cooker) ",
				"spend most of their time. She's currently eating what looks like a fish. You sit down beside ",
				"her for a while, expressing your unending love for her and your desire for companionship.",
			]),
			P([
				"Despite your best poker face, she seems to have figured out that you're asking for food. She ",
				"refuses to give you any, but you can definitely smell it from down here.",
			]),
			P([
				"Mmmmm, herring. Delicious food, delicious food. This one seems to be slathered in tomato sauce, ",
				"rather than being eaten plain with salt. Not that there's anything wrong with tomatoes of course; ",
				"but you like the grease and fish much more.",
			]),
			P([
				"I suppose it's a red herring, then.",
			]),
		],
		footprints: () => P([
			//Possible evidence
			"They look like a size meow, or maybe a bit bigger.",
		]),
	},
};

function TRAVELBUTTONS(dest) {
	let have_dest = false;
	(dest||all_locations).forEach(d => !state[d] && (have_dest = true));
	return DIV({class: "travelbuttons"}, [
		"Travel to: ",
		(dest||all_locations).map(d => BUTTON({type: "button", "data-dest": d, disabled: !!state[d]}, locations[d].dest)),
		!have_dest && BUTTON({type: "button", "data-dest": "denoument"}, "Announce your results"),
	]);
}

const render_scene = {
	intro() {return [
		...markdown["part-one-the-shocking-discovery"],
		TRAVELBUTTONS(["crimescene"]),
	]},
	crimescene() {return [
		...markdown["part-two-the-crime-scene"],
		TRAVELBUTTONS(),
	]},
	shop() {return [
		...markdown["shop"],
		TRAVELBUTTONS(),
	]},
	fission() {return [
		...markdown["fish-and-chippery"],
		TRAVELBUTTONS(),
	]},
	denoument() {return [
		...markdown["submit-your-findings"],
		//TODO: This is where you select a person to accuse (or "no crime happened" but maybe disable that
		//because the cat will always see that it's a crime to have no tuna), list the supporting evidence,
		//and submit the case to the human.
	]},
}

//Return a string of length characters with consecutive code points starting at start
//eg unicode_range(65, 4) ==> "ABCD"
function unicode_range(start, length) {
	const cp = [];
	for (let i = 0; i < length; ++i) cp.push(start + i);
	return String.fromCodePoint(...cp);
}

function repaint() {
	replace_content(main, [
		loc && DIV({id: "status"}, [
			DIV([
				"Time: ",
				SPAN({id: "time_spent"}, unicode_range(0x1f550, here.time_spent)),
				SPAN({id: "time_remaining"}, unicode_range(0x1f550 + here.time_spent, loc.time_limit - here.time_spent)),
			]),
			DIV({style: "display: flex; justify-content: space-evenly;"}, [
				BUTTON({type: "button", id: "shownotes"}, "Check notes"), //Need a better label
			]),
		]),
		render_scene[state.scene](),
	]);
}
repaint();

on("click", "[data-dest]", e => {
	//Travel to a new location
	state.scene = e.match.dataset.dest;
	//NOTE: Currently time_spent is always equal to Object.keys(investigated).length, but
	//this may not always hold (if some investigations take more or less time). For now,
	//retaining the separate variable, but the design elegance of "everything takes 1 time
	//unit" is probably worth keeping.
	here = state[state.scene] = {investigated: { }, time_spent: 0};
	loc = locations[state.scene];
	repaint();
});

let fullinvestigate = null;
on("click", "[data-investigate]", e => {
	const item = e.match.dataset.investigate;
	//Investigate an item in the current scene.
	//You can always get the basic info (even if you're out of time), but getting
	//detailed information costs time, unless you already looked at this (in which
	//case you will be shown the same info again).
	//NOTE: We assume here that there is only ever one button for a given investigation
	//target. It would be confusing for the player to have multiple anyway.
	const detail = here.investigated[item];
	replace_content(DOM("#inspectinfo"), [
		investigate_basic[state.scene][item],
		detail,
	]);
	const seen = DOM("#inspect-full").hidden = !!detail;
	if (!seen) fullinvestigate = e.match;
	DOM("#inspectdlg").showModal();
});

on("click", "#inspect-full", e => {
	DOM("#inspectdlg").close();
	const item = fullinvestigate.dataset.investigate;
	++here.time_spent;
	here.investigated[item] = [
		lindt.HR(),
		investigate_full[state.scene][item](),
	];
	fullinvestigate.classList.add("seen");
	repaint();
	fullinvestigate.click(); //Close and re-show the dialog, now with more info.
});

const cat_quotes = {
	generic: [ //Generic quotes that could always be used (if nothing else is more suitable)
		"Do cats eat bats? Do bats eat cats?",
		"Put cats in the coffee and mice in the tea",
		"The truth is revealed to those too small to be deceived. But truth is that which, when you stop believing in it, does not cease to be.",
		"My natural curiosity is tempered with caution - thus I've lived long.",
		"As knowing where you're going is preferable to being lost, ask.",
		"Time to raise some havoc! The dogs of war are loose!",
		"Observe, learn, and react.",
		"Steps to enlightenment brighten the way, but the steps are steep. Take them one at a time.",
		"A reflection sometimes exposes more reality than the object it echoes.",
	],
	time_expired: [ //You're out of time here. Move on.
		"You're sure to get somewhere, if you walk long enough.",
		"Only a few find the way. Some don't recognize it when they do. Some don't ever want to.",
		"The proper order of things is often a mystery to me. You, too?",
		"It's rude to eat and run, but sometimes it's unavoidable.",
	],
	get_started: [ //You got here and haven't investigated yet.
		"Every adventure requires a first step. Trite but true, even here.",
		"The uninformed must improve their deficit, or die.",
	],
	unused: [ //Unused lines that could be applied to special situations
		"Always collect what's useful. Reject only your ignorance, and you may survive.",
		"Confront what frightens or offends you. Reckless or insulting talk should never go unchallenged.",
		"Doors have locks, locks need keys, which you don't have.",
	],
};

function random_choice(arr) {
	return arr[Math.floor(Math.random() * arr.length)];
}

on("click", "#shownotes", e => {
	let situation = "generic";
	if (here.time_spent === 0) situation = "get_started";
	if (here.time_spent >= loc.time_limit) situation = "time_expired";
	replace_content("#notesinfo", [
		DIV({id: "catquote"}, [
			'"', random_choice(cat_quotes[situation]), '"',
			IMG({src: "https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_689922c1be4f449faf672e4a45b78b2c/static/light/2.0", alt: "- Cheshire Cat", title: "Cheshire Cat"}),
		]),
		P("This is where I keep track of everything that matters. Checking this is done at the speed of cat, so it won't consume any investigation time."),
		P([
			`We currently have ${loc.time_limit - here.time_spent} out of ${loc.time_limit} time left in this location. `,
			SPAN({id: "time_spent"}, unicode_range(0x1f550, here.time_spent)),
			SPAN({id: "time_remaining"}, unicode_range(0x1f550 + here.time_spent, loc.time_limit - here.time_spent)),
			" Brief looks at suspicious things don't take long, but a full inspection costs one time.",
		]),
	]);
	DOM("#notesdlg").showModal();
});
